version: "2"
services:
  web:
    build: .
    ports:
      - 5050:8080
    depends_on:
      - db
  db:
    container_name: postgresdb
    build:
      context: ./
      dockerfile: Dockerfile-db
    volumes:
      - lms_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  lms_db: {}
